# Generated by Django 5.1 on 2024-09-04 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='volunteer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'volunteer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adoptions_as_volunteer', to=settings.AUTH_USER_MODEL),
        ),
    ]
